### ISSUE TITLE
0.11.x - Add a method to disable use of prettyPrintJs in AbstractJsContentGenerator

### ISSUE THREAD

**Issue by Blystad** [dandelion/dandelion#44]
`ScriptingUtils.prettyPrintJs` which is used in `AbstractJsContentGenerator#getAssetContent(HttpServletRequest)` uses considerable time just to make the Javascript more readable. Readable javascript is useful during development but wasted in production.

As one can see in the below, this takes significant processing time:
![http://i.imgur.com/mMopozD.png](http://i.imgur.com/mMopozD.png)

Both of those are because of prettyPrintJs.

**Comment by tduchateau** [comment]
Thanks!

I've just restored the option that allows to disable asset pretty printing.
It is now enabled by default with the dev profile, and disabled by default in the prod profile.

**Comment by gseifert** [comment]
This is still an issue in AbstractJsPlaceholderContentGenerator

**Comment by alexandrepetrillo** [comment]
I create pull request : https://github.com/dandelion/dandelion/pull/120
