### ISSUE TITLE
0.11.0 - `ddl-debug` links uses absolute root URL

### ISSUE THREAD

**Issue by Blystad** [dandelion/dandelion#48]
If I activate `ddl-debug` on a non-root page, for instance: `http://localhost:9000/devices/view?id=15&ddl-debug`

The URLs on the ddl-debug page is always absolute, e.g:
`http://localhost:9000/?ddl-debug&ddl-debug-page=options`

Instead of the expected:
`http://localhost:9000/devices/view?id=15&ddl-debug&ddl-debug-page=options`

**Comment by tduchateau** [comment]
Thx for flagging this up!
