### ISSUE TITLE
0.11.0 - Assets gets cached even in development mode

### ISSUE THREAD

**Issue by Blystad** [dandelion/dandelion#49]
Hey,

So, I use the Asset bundles. When developing locally I want the assets to update when changes so I don't have to restart the server every time I make a change. 

Assets gets rewritten into something like this:
`/dandelion-assets/b2cccf882d2367d952fcc59dcd6030b4/css/style-1.css`

If I update this in my IDE and update it, then the change is not presented. The contents here gets cached no matter what I do. I've tried `ddl-reload`, I've tried to add extra query parameters to play with the cache, but nothing works.

If I access the stylesheet directly, for example by going to `/static/css/style.css` then the update is presented.

Regards,
Arne-Christian

**Comment by tduchateau** [comment]
Starting from v0.11.0, the `dev` profile is enabled by default.
In this profile, asset automatic verisoning is enabled by default, and uses the contents of each asset to generate a fingerprint and insert it in the asset's name.
__Unless__ you specify a version in the declaration of assets, in which case the version is "forced" to what you set.
So try to remove the version from the bundle declaration as shown below:
````
{
   "assets": [
      {
         "version" : "1", <=== Remove this line
         "locations" : {
            "webapp" : "/static/css/style.css"
         }
      }
   ]
}
````

**Comment by Blystad** [comment]
I tried removing it, but it still seemed to be cached, so I just disabled the feature.

**Comment by tduchateau** [comment]
Problem indentified. Will be fixed in the next snapshot!
