### ISSUE TITLE
Bundles could not be loaded from jar

### ISSUE THREAD

**Issue by BSass** [dandelion/dandelion#78]
I just installed datatables-jsp 1.1.0 as described in manual. My table shows up with the data, but no controls (like sorting, pageLength, etc). Then I saw that my browser wasn't able to load any of the requested js/css ressources. I always got a 404.
After some time I figured out, that when I override the default bundles and delete the "jar" location everything works fine.
What is my mistake?

**Comment by tduchateau** [comment]
By removing the `jar` location in bundle, you tell Dandelion to use the remaining location (`remote`), that's why everything works fine.

You've probably missed the new [requirements](http://dandelion.github.io/components/datatables/1.1.0/docs/html/#2-requirements): Servlet 3.0+ container.

**Comment by BSass** [comment]
Thanks for your reply. I use Java 7, tomcat-7.0.33 and in my web.xml I use this header:
`<web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
   version="3.0">`
So I think I met all requirements, right?

**Comment by tduchateau** [comment]
Absolutely. Question: do you use Spring MVC?

**Comment by BSass** [comment]
Yes I use Spring (MVC) 3.2.13.

**Comment by tduchateau** [comment]
OK. Same question as in https://github.com/dandelion/dandelion/issues/68#issuecomment-128070953

Have you configured a default servlet handler?

**Comment by BSass** [comment]
You are right. That solved the problem. Thank you!

**Comment by tduchateau** [comment]
Great! I'll update the docs accordingly
