### ISSUE TITLE
Thymeleaf dandelion:placeholder support

### ISSUE THREAD

**Issue by joshsadam** [dandelion/dandelion#88]
Hi @tduchateau 
Thanks for todays update, especially the fix for issue #73 .  Is there a thymeleaf attribute for `dandelion:placeholder`?  I cannot find it in the docs or source although I see the JSP version. 
Thanks
Josh

**Comment by tduchateau** [comment]
Hi Josh,
Please have a look at http://dandelion.github.io/components/core/1.1.1/docs/html/#b-3-code-ddl-placeholder-code-attributes

**Comment by joshsadam** [comment]
Apparently again, I cannot read.  Thanks

**Comment by tduchateau** [comment]
What do you mean?
You get a 404? Or maybe a proxy issue?

**Comment by joshsadam** [comment]
Sorry, what I meant is that I thought I looked everywhere for that in the docs after finding the jsp tag info for placeholders and just clearly missed it - your link bring me directly to it.  It is working exactly as I thought it would in our code.  Thank you and your team for working so hard on this.
